export const FETCH_DATA = `FETCH_DATA`
export const FETCH_DATA_SUCCESS = `FETCH_DATA_SUCCESS`
export const FETCH_DATA_ERROR = `FETCH_DATA_ERROR`

export const SELECT_TIMESLOT = `SELECT_TIMESLOT`
export const REMOVE_TIMESLOT = `REMOVE_TIMESLOT`